### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Sahilsk99** [khushhallchandra/DSTL#1]
Hello brother you are such great person bro the projects that you created its great
Actually  I am using your script in my project and along with its datasets but in my system its throwing Memory Error in line number 204 and I am using python 3.7 and windows 10 machine with 8 GB RAM 

Traceback (most recent call last):
  File "C:\Users\Sahil Sheikh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'transpose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Projects Data/Satellite Proejct/myCode.py", line 467, in <module>
    model = train_net()
  File "D:/Projects Data/Satellite Proejct/myCode.py", line 368, in train_net
    x_trn, y_trn = get_patches(img, msk)
  File "D:/Projects Data/Satellite Proejct/myCode.py", line 204, in get_patches
    x, y = 2 * np.transpose(x, (0, 3, 1, 2)) - 1, np.transpose(y, (0, 3, 1, 2))
  File "C:\Users\Sahil Sheikh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "C:\Users\Sahil Sheikh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\Sahil Sheikh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\Sahil Sheikh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError

BRo can you help me to solve this problem

**Comment by meetps** [comment]
Bro https://downloadmoreram.com/

**Comment by Sahilsk99** [comment]
is it occurs due to insufficient RAM memory ?
